"use client";

import { motion } from "framer-motion";
import React from "react";
import { Zap, TrendingUp, Target } from "lucide-react";
import Link from "next/link";


const insightsPool = [
    {
        observation: "Your `Ad8Hoarding` campaign in Bengaluru is creating a 22% spike in brand searches.",
        recommendation: "Amplify this with a targeted `Ad8Mobi` push in the same area to maximize impact."
    },
    {
        observation: "Audience engagement for your `Ad8Radio` spots drops by 40% after the 15-second mark.",
        recommendation: "Condense your message into a shorter, high-impact 15-second creative for this channel."
    },
    {
        observation: "Competitor ad spend has increased by 30% on `Ad8Social` platforms in the last 48 hours.",
        recommendation: "Launch a counter-campaign on `8DigiAd` screens in high-footfall areas to capture market share."
    },
     {
        observation: "Sentiment analysis shows a 15% increase in positive mentions following your `Ad8TV` campaign.",
        recommendation: "Leverage this positive sentiment by launching a `Zeedback` survey to gather testimonials."
    }
];

const latestLaunches = [
    {
        title: "Hyperlocal Weather Sync",
        description: "Automatically adjust your `8DigiAd` creative based on real-time local weather conditions.",
        icon: Zap,
    },
    {
        title: "Predictive Trend Analysis",
        description: "Our AI now forecasts emerging market trends, allowing you to create campaigns before your competitors.",
        icon: TrendingUp,
    },
    {
        title: "Cross-Channel Audience Matching",
        description: "Identify and target the same user segments across both `Ad8OOH` and `Ad8Social` for a unified brand message.",
        icon: Target,
    }
];

const InsightPage = () => {
    return (
        <div className="bg-black text-white">
            {/* 1. Hero Section */}
            <motion.section 
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                transition={{ duration: 1 }}
                className="pt-40 pb-20 text-center"
            >
                <div className="mx-auto max-w-4xl px-6 lg:px-8">
                    <motion.h1 
                        initial={{ opacity: 0, y: 20 }}
                        animate={{ opacity: 1, y: 0 }}
                        transition={{ duration: 0.8, delay: 0.2 }}
                        className="font-sans text-5xl md:text-7xl font-bold tracking-tight"
                    >
                        The Power of Clarity.
                    </motion.h1>
                    <motion.p 
                        initial={{ opacity: 0, y: 20 }}
                        animate={{ opacity: 1, y: 0 }}
                        transition={{ duration: 0.8, delay: 0.4 }}
                        className="mt-6 text-lg md:text-xl text-white/70"
                    >
                        This is more than a demo. It's a glimpse into the future of advertising strategy. See how Aura transforms complex data into decisive action.
                    </motion.p>
                </div>
            </motion.section>

            {/* 2. Strategic Insights Gallery */}
            <section className="py-20 sm:py-32">
                <div className="mx-auto max-w-7xl px-6 lg:px-8">
                    <div className="text-center mb-16">
                        <h2 className="font-sans text-4xl sm:text-5xl font-bold tracking-tight">Strategic Insights Showcase</h2>
                        <p className="mt-4 text-lg md:text-xl text-white/70 max-w-3xl mx-auto">
                            Below are examples of real-time, actionable recommendations generated by the Aura AI engine.
                        </p>
                    </div>
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
                        {insightsPool.map((insight, index) => (
                            <motion.div
                                key={index}
                                initial={{ opacity: 0, y: 20 }}
                                whileInView={{ opacity: 1, y: 0 }}
                                viewport={{ once: true, amount: 0.5 }}
                                transition={{ duration: 0.6, delay: index * 0.1 }}
                                className="relative p-8 bg-black border border-white/10 rounded-2xl"
                            >
                                <div className="absolute -inset-px rounded-2xl bg-gradient-to-br from-blue-600/20 to-sky-600/20 blur-lg -z-10"></div>
                                <p className="text-lg leading-relaxed text-white/90">
                                    {insight.observation}
                                </p>
                                <hr className="my-4 border-white/10" />
                                <p className="text-lg leading-relaxed">
                                    <strong className="font-semibold text-transparent bg-clip-text bg-gradient-to-r from-blue-400 to-sky-400">
                                        Aura Recommends:
                                    </strong> {insight.recommendation}
                                </p>
                            </motion.div>
                        ))}
                    </div>
                </div>
            </section>

            {/* 3. Latest Launches Section */}
            <section className="py-20 sm:py-32 bg-white/5">
                <div className="mx-auto max-w-7xl px-6 lg:px-8 text-center">
                    <motion.div
                        initial={{ opacity: 0, y: 20 }}
                        whileInView={{ opacity: 1, y: 0 }}
                        viewport={{ once: true, amount: 0.5 }}
                        transition={{ duration: 0.8 }}
                    >
                        <h2 className="font-sans text-4xl sm:text-5xl font-bold tracking-tight">Latest Launches</h2>
                        <p className="mt-6 text-lg md:text-xl text-white/70 max-w-3xl mx-auto">
                            Our platform is constantly evolving. Here are some of our newest capabilities designed to give you a competitive edge.
                        </p>
                    </motion.div>
                    <div className="mt-16 grid grid-cols-1 md:grid-cols-3 gap-8">
                        {latestLaunches.map((launch, index) => (
                             <motion.div
                                key={launch.title}
                                initial={{ opacity: 0, y: 20 }}
                                whileInView={{ opacity: 1, y: 0 }}
                                viewport={{ once: true, amount: 0.5 }}
                                transition={{ duration: 0.6, delay: 0.2 + index * 0.2 }}
                                className="p-8 bg-black border border-white/10 rounded-xl text-left"
                            >
                                <launch.icon className="w-10 h-10 text-blue-400" />
                                <h3 className="mt-6 text-xl font-bold">{launch.title}</h3>
                                <p className="mt-2 text-white/70">{launch.description}</p>
                            </motion.div>
                        ))}
                    </div>
                </div>
            </section>

             {/* 4. Final CTA */}
            <section className="py-20 sm:py-32">
                <div className="mx-auto max-w-7xl px-6 lg:px-8 text-center">
                    <motion.div
                        initial={{ opacity: 0, y: 20 }}
                        whileInView={{ opacity: 1, y: 0 }}
                        viewport={{ once: true, amount: 0.5 }}
                        transition={{ duration: 0.6 }}
                    >
                        <h2 className="font-sans text-4xl sm:text-5xl font-bold tracking-tight">
                            Ready for a Personalized Demo?
                        </h2>
                        <p className="mt-4 text-lg sm:text-xl text-white/70 max-w-2xl mx-auto">
                            Let our team show you how Aura can be tailored to your specific business goals and challenges.
                        </p>
                        <div className="mt-10">
                            <Link
                                href="/contact"
                                className="inline-block px-10 py-5 text-xl font-semibold bg-white text-black rounded-full hover:bg-gray-200 transition-colors"
                            >
                                Schedule Your Demo
                            </Link>
                        </div>
                    </motion.div>
                </div>
            </section>
        </div>
    );
};

export default InsightPage;